import = [
  #"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
opacity = 0.8
blur = true
startup_mode = "Maximized"

[font]
normal = {family = "JetBrainsMono Nerd Font", style = "Regular"}
size = 12.5
